# typed: false
# frozen_string_literal: true

# NOTE: This file is automatically generated and updated by the release workflow.
# The version, URLs, and SHA256 checksums are automatically populated during releases.
# Do not manually edit this file - it will be overwritten on the next release.

class Galileoctl < Formula
  desc "Galileo CLI for quick troubleshooting and log bundle collection"
  homepage "https://github.com/rungalileo/galileoctl"
  version "0.2.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rungalileo/galileoctl/releases/download/v0.2.2/galileoctl-darwin-arm64"
      sha256 "1aab7eef6fc5396f87f4ecb930f0a7bde8ebb8588b0c76a3a5321c143b1293a7"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rungalileo/galileoctl/releases/download/v0.2.2/galileoctl-linux-amd64"
      sha256 "ae8b2a68fb5cc4039b8de81186216b349bfcabc32a5208e89cc6fab135fbdb85"
    end
  end

  def install
    binary_name = if OS.mac?
      "galileoctl-darwin-arm64"
    elsif OS.linux?
      "galileoctl-linux-amd64"
    end
    
    bin.install binary_name => "galileoctl"
  end

  test do
    system "#{bin}/galileoctl", "version"
  end
end

