# typed: false
# frozen_string_literal: true

# NOTE: This file is automatically generated and updated by the release workflow.
# The version, URLs, and SHA256 checksums are automatically populated during releases.
# Do not manually edit this file - it will be overwritten on the next release.

class Galileoctl < Formula
  desc "Galileo CLI for quick troubleshooting and log bundle collection"
  homepage "https://github.com/rungalileo/galileoctl"
  version "0.7.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rungalileo/galileoctl/releases/download/0.7.4/galileoctl-darwin-arm64"
      sha256 "5323c49fbd1893b23e1226d63b35ff218273723414247034d96314486f60c614"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rungalileo/galileoctl/releases/download/0.7.4/galileoctl-linux-amd64"
      sha256 "3bbbf7d9374653bcee36b41714b23cedf762981e6002247e2f244b253606e2d4"
    end
  end

  def install
    binary_name = if OS.mac?
      "galileoctl-darwin-arm64"
    elsif OS.linux?
      "galileoctl-linux-amd64"
    end
    
    bin.install binary_name => "galileoctl"
  end

  test do
    system "#{bin}/galileoctl", "version"
  end
end
