# typed: false
# frozen_string_literal: true

# NOTE: This file is automatically generated and updated by the release workflow.
# The version, URLs, and SHA256 checksums are automatically populated during releases.
# Do not manually edit this file - it will be overwritten on the next release.

class Galileoctl < Formula
  desc "Galileo CLI for quick troubleshooting and log bundle collection"
  homepage "https://github.com/rungalileo/galileoctl"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rungalileo/galileoctl/releases/download/v0.4.0/galileoctl-darwin-arm64"
      sha256 "910bb5624457a490ffd8ae39400b51ea656d9fc36fe737d8c4a29fb690a17a5b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rungalileo/galileoctl/releases/download/v0.4.0/galileoctl-linux-amd64"
      sha256 "72f43adaa4a5f61a810584413732e38226a9f757ca4b6b11048c7a65ad572da4"
    end
  end

  def install
    binary_name = if OS.mac?
      "galileoctl-darwin-arm64"
    elsif OS.linux?
      "galileoctl-linux-amd64"
    end
    
    bin.install binary_name => "galileoctl"
  end

  test do
    system "#{bin}/galileoctl", "version"
  end
end

